### ISSUE TITLE
Audio crackling in Quake 2

### ISSUE THREAD

**Issue by thekovic** [m64p/m64p#178]
**Describe the bug**
Audio crackling in Quake 2.

**To Reproduce**
1. Play the game. Very noticeable in Level 2 on the bridge and when setting off the explosives but many different sounds seem to crackle.

**Screenshots**
Video of gameplay here: https://www.youtube.com/watch?v=F1iD1nkZhDk

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - i5 8300H
 - GPU: GTX 1050Ti

**Additional context**
Default emulator settings except deinterlacing set to Weave. Expansion Pak enabled, CountPerOp = 0.

**Comment by RokkumanX** [comment]
Could you try this out?

[mupen64plus-audio-sdl_v2.5.9-22-gaf6af5b_x64](https://github.com/loganmc10/m64p/files/6630689/mupen64plus-audio-sdl2.zip)

This is the mupen64plus-audio-sdl version instead of mupen64plus-audio-sdl2 included with m64p.
Don't be discouraged that it's named mupen64plus-audio-sdl2.dll, it have to be for m64p to recognize it.

The mupen64plus-audio-sdl is based off [this](https://ci.appveyor.com/project/Narann/mupen64plus-audio-sdl/builds/37865824/job/2ovux85tlmhvswal) release which is from original Mupen64Plus.

You'll have to refer to the `mupen64plus.cfg` file enable to change settings for this, but another user said it fixed his crackling sound issues.

**Comment by DaRkL3AD3R** [comment]
Ever since I dropped this dll into my directory, the emulator refuses to load if the audio dll is present. Deleting the file will let it load but with a failed to load plugin error obviously. What's up with that?

**Comment by RokkumanX** [comment]
Are you referring to my post with the .dll? @DaRkL3AD3R 

I got no issues with that audio plugin and the said plugin is from the official mupen64plus project so it's not something I built myself.

I tested this with the July 5th version of m64p and everything loads correctly.

![working](https://user-images.githubusercontent.com/85066613/125429359-669bdfae-9ef1-4dc5-86ea-ae884bd2a9d4.png)

**Comment by DaRkL3AD3R** [comment]
Yeah the .dll in your post above. The first time I went to use it, M64P would fail to load for the remainder of the boot. It would get hung up in the background running in task manager but never presented a window. The odd thing is, after rebooting my PC and trying again, I can now swap the dll in and out without any issues. I'm not sure where the conflict was but it definitely came from swapping in that older dll.

I guess for now that whole situation can be ignored because it seems to have been a one off thing for me so unless someone else can reproduce the issue and verify it, then it could have just been something unique to my setup.

**Comment by RokkumanX** [comment]
You might want to hold on to the build you are using now of m64p because there is changes being made that currently blocks you from using alternative video plugins like angrylion-rdp-plus and it might be days away from being able to use different RSP and audio plugins.

Just a heads-up.

**Comment by DaRkL3AD3R** [comment]
Appreciate the look out. And just for the final record, can confirm that the older audio plugin does solve the crackling audio.

**Comment by RokkumanX** [comment]
It truly makes me glad to hear that it solves the crackling audio!

**Comment by RokkumanX** [comment]
Scratch my other comment from an hour ago, the changes have been made, there is no way to use any of the other plugins anymore.

RIP m64p....good night sweet prince.

**Comment by arilando** [comment]
I'm having this issue in Ocarina of Time. And the emulator will not run with the provided fix, even after a PC reboot.

**Comment by RokkumanX** [comment]
You can't use any other plugins except those shipped with the project these days, it's a complete plugin lockdown.

You'll have to see if you can find an older build from around 5th of July or lower.
