### ISSUE TITLE
Can't save on Donkey Kong 64

### ISSUE THREAD

**Issue by bhlaab** [m64p/m64p#241]
This is a somewhat known problem. I had to go into mupen64plus.ini and set the save type to eeprom 16k.

>  [11DA2A2D0E91074BB8FF1FCB029535FD]
> GoodName=Donkey Kong 64 - Tag Anywhere (V5) (U)
> CRC=31739C69 A99E3CB2
> RefMD5=9EC41ABF2519FC386CADD0731F6E868C
> SaveType=Eeprom 16KB

Now when I start a new game, I can save. The problem is, I already played halfway through the game using save states, and if I load a save state, the eeprom save function doesn't work anymore.

I've heard DK64 has a bug where if you don't save and quit, eventually it hard crashes. I would like to avoid that without replaying everything if I can. Is there anything I can do about this?

**Comment by loganmc10** [comment]
Donkey Kong 64 - Tag Anywhere already used 16KB eeprom, since it has ```RefMD5=9EC41ABF2519FC386CADD0731F6E868C```, which means it references this entry for it's settings:
```
[9EC41ABF2519FC386CADD0731F6E868C]
GoodName=Donkey Kong 64 (U) [!]
CRC=EC58EABF AD7C7169
SaveType=Eeprom 16KB
Players=4
CountPerOp=1
Rumble=Yes
```
The Tag Anywhere entry was added in the Dec 3 release (https://github.com/m64p/m64p/releases/tag/v2021.12.3) so if you started your game before then, then yes it probably created a bad save file.

As far as fixing the save state goes, no I don't think there is anything that can be done.
