### ISSUE TITLE
Resident Evil 2 (Only US and Japanese) hangs after the 64 logo.

### ISSUE THREAD

**Issue by AkihitoZero5454** [m64p/m64p#245]
I'm trying to play Resident Evil 2 but after the 64 logo, it hangs. Do I have to deselect the expansion pak option or is it a bug?

**Comment by AkihitoZero5454** [comment]
Well I found out if you select Load and Options and attempt to go back to the title screen. It'll hang with the same black screen (All versions).

**Comment by loganmc10** [comment]
I can't reproduce this, I was able to get in-game using the USA and Europe ROM

**Comment by thekovic** [comment]
@AkihitoZero5454 What are your ROM's hashes? You can see it when you open the game and then click Emulation->View Log. I was able to get into the game using a ROM with the hash 1ADD2C0217662B307CDFD876B35FBF7A

**Comment by AkihitoZero5454** [comment]
@thekovic 1ADD2C0217662B307CDFD876B35FBF7A on Rev 1 USA

**Comment by AkihitoZero5454** [comment]
@thekovic Fixed it! I had to turn on Superscaled Reads, Dither and Synchronous RDP.

**Comment by RokkumanX** [comment]
The only known option required for BioHazard 2/Resident Evil 2 to boot/go ingame is Synchronous RDP.
Superscaled Reads and Dither have nothing to do with whether if the game will boot/go ingame or not.

This issue can be closed safely! @loganmc10 

Also I had this same issue with the Project64 version of the plugin a couple of days ago, turned out the option for toggle between Synchronous RDP ON/OFF wasn't implemented in the GUI.

Thanks to Rosalie241 the option was later implemented and BioHazard 2 was working happily again!
