### ISSUE TITLE
In the DK64 intro Donkey Kong fails to grab the vine (JP version).

### ISSUE THREAD

**Issue by jeltaqq** [m64p/m64p#274]
**Describe the bug**
In the DK64 intro, the demos for the game which Donkey Kong fails to grab the vine.
The US version is accurate, but the JP version have bad timing.

**To Reproduce**
1. Start playing DK64 JP version.
2. Wait on the title screen.
3.    Compare the speed of the demo on m64p with that of the demo running on US version.

**Expected behavior**
The demo should run at a comparable to US version.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - GPU: Nvidia Geforce 750ti

**Additional context**
m64p v2022.07.11
ROM Hash value matches mupen64plus.ini
5B677F4BF93D6578252FCAD2C8CEB637

**Comment by loganmc10** [comment]
Thanks, this is a good point actually. Given the relative inaccuracy of the emulator, it may be quite a while before timing gets accurate enough for it to work across all 3 versions (USA, Europe, Japan).

However, I believe I did find timing values that get DK to at least swing on one of the vines in all 3 versions: https://github.com/m64p/m64p/releases/tag/v2022.07.12

This is probably a good indication that the timing values are closer to what they should be.

**Comment by jeltaqq** [comment]
v2022.07.12 is more accurate. Thank you for your hard work.

**Comment by loganmc10** [comment]
I just tested the latest version and DK hits the vines in all 3 versions. Sometimes he can miss slightly, I believe because of the randomness code that is in place to simulate randomness in real life, which may make things off a bit. However, I think this is close enough that this can be considered close. I think it's not bad considering that m64p doesn't emulate the CPU pipeline like some other N64 emulators.
